### PR TITLE
Rosdep init called with sudo

### PR DESCRIPTION
**Pull request by samlcharreyron**
rosdep init needs to be called with sudo. Should fix https://github.com/ethz-msrl/Tesla_core/issues/176

### CODE REVIEW

**Comment by samlcharreyron** [comment]
@qboehler, do you have a clean ubuntu VM available to test this? I think it should fix the problem.

**Comment by qboehler** [comment]
I am going to try this yes. How do you explain you did not have the problem on the docker image?

**Comment by qboehler** [comment]
@samlcharreyron yep that works.

**Comment by samlcharreyron** [comment]
> I am going to try this yes. How do you explain you did not have the problem on the docker image?

because by default docker containers run everything as sudo so you don't catch this kind of problem unfortunately :\

**Pull request merged**
